### ISSUE TITLE
Cannot access directories from within LibrePCB

### ISSUE THREAD

**Issue by ubruhin** [LibrePCB/librepcb-snap#2]
See https://librepcb.discourse.group/t/librepcb-doesnt-see-directories/275.

**Comment by dbrgn** [comment]
I assume that snap - like flatpak - does sandboxing of the file system. In flatpak, by default the home directory is accessible but no other directories. Basically, every application gets its own virtual filesystem.

https://core.docs.ubuntu.com/en/guides/intro/security

I'm not sure what the best practice here is. But if every snap has full write access to the entire file system, then one of the nicest aspects of using snaps versus regular installs is being lost.

Maybe the user can selectively grant full FS access to certain installed snaps?

**Comment by ubruhin** [comment]
Yeah that sounds reasonable. I don't know how Snap handles this exactly and if the user is able to kind of whitelist specific directories, I might check this out when updating the snap package the next time...

**Comment by ubruhin** [comment]
For the record, I realized that the "removable media" permission needs to be granted manually by the user. Then the application gets access to `/media` and `/mnt` in addition to `$HOME`. For example in the Ubuntu Software Center:

![image](https://user-images.githubusercontent.com/5374821/130319527-024cf494-b976-451f-911e-80c273885469.png)

Maybe we should ask the snapd maintainers for auto-connecting the "removable-media" interface, as described [here](https://snapcraft.io/docs/interface-management#heading--auto-connections) (although I'm not sure if LibrePCB meets the requirements to get this auto-connection). But I'd say this is nothing urgent now since users can already fix it easily.

**Comment by ubruhin** [comment]
Resolved since we got the `removable-media` auto-connection some time ago.
